### PR TITLE
ENH: theme & icons

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/mne-tools/mne-python/pull/10456#issuecomment-1086318010 and updates Qt icons so that they adapt to the theme.

light | dark
--|--
image | image

### CODE REVIEW

**Comment by larsoner** [comment]
And so that we are PyQt6 / non-`resource.py` compatible, right?

**Comment by GuillaumeFavelier** [comment]
> And so that we are PyQt6 / non-resource.py compatible, right?

Indeed, it's a step forward because `PyQt6` dropped the Qt resource system.

**Comment by GuillaumeFavelier** [comment]
With the new icon `overview_bar`:

light | dark
--|--
image | image

**Comment by larsoner** [comment]
Beautiful!

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
