### PR TITLE
FIX: ipython support

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR uses `ipython` magic to fix the "freezing" happening when `block=False` in an Ipython environment.

It also adds dependency to `scooby` to detect the aforementioned ipython environment.

Closes https://github.com/mne-tools/mne-qt-browser/issues/72
Related to https://github.com/mne-tools/mne-python/pull/10472

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
works for me and especially since scooby is already a dependancy of mne-python via pyvista

thx @GuillaumeFavelier 

I'll let @hoechenberger merge if happy

**Comment by hoechenberger** [comment]
Amazing! It works for me!

@agramfort I cannot merge due to lack of privileges :'(

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
We should cut a release once this is merged

**Comment by marsipu** [comment]
Thank you @GuillaumeFavelier, this is a great solution.

**Comment by marsipu** [comment]
> We should cut a release once this is merged

Done

**Comment by hoechenberger** [comment]
Great!

**Pull request merged**
