### PR TITLE
ENH: Add icons

### PR DESCRIPTION
**Pull request by marsipu**
This PR adds custom icons from [Google's material design](https://github.com/google/material-design-icons).

### CODE REVIEW

**Comment by larsoner** [comment]
@hoechenberger this is probably for you :)

**Comment by agramfort** [comment]
can you share a screenshot? 🙏

**Comment by hoechenberger** [comment]
Screenshot 2022-02-10 at 08 59 47


Good job so far, already much better than before! I'd have some recommendations for further improvements if you're interested. But this is already a great step up, thank you!

**Comment by marsipu** [comment]
@hoechenberger thank you for the screenshot.
I asked Guillaume which icons he used for the pyvista-backend and added the icons from [Google](https://fonts.google.com/icons?selected=Material+Icons+Outlined). Then I adapted some of them in Inkscape (less channels, less time).
I am open for improvements and suggestions,  @hoechenberger what do you have in mind?

**Comment by marsipu** [comment]
@hoechenberger You said you had some suggestions for further improvements?

**Comment by hoechenberger** [comment]
… just give me until noon … 😅

**Comment by hoechenberger** [comment]
@marsipu Sorry for holding you off here, I'm just too busy with other stuff right now, my apologies. Please go ahead and merge if you're happy, and once I have more time again, we can iterate with additional tweaks. This PR is already a huge step up so I think it should be merged ASAP. We can make things even better at a later time!

**Comment by hoechenberger** [comment]
@larsoner This branch is en par with `main`, maybe try just restarting CI?
(I cannot do it for lack of permissions – I'm not an admin / maintainer of this project)

**Comment by larsoner** [comment]
Okay, now even more CIs failed :)

**Comment by hoechenberger** [comment]
🙈

**Comment by marsipu** [comment]
I think the fails are fixed in #54 which just got merged. Try rebasing again on main now

**Pull request merged**
