### PR TITLE
MAINT: Patch old MNE ver test

### PR DESCRIPTION
**Pull request by larsoner**
Hopefully green then merge the 0.5.2 release

### CODE REVIEW

**Comment by drammock** [comment]
wild, I never would have thought to actually use `patch` in the CI workflow like that. 🎩

**Comment by mscheltienne** [comment]
And I had no idea `patch` even existed!

**Comment by larsoner** [comment]
I got the idea from needing to patch various feedstocks (dipy, mayavi, etc.) for conda-forge 🙄 

For future reference it was fairly easy -- I went to `mne-python`, checked out `maint/1.4`, made the changes I wanted, and created a patch as:
```
git diff > ../mne-qt-browser/.github/workflows/mne_1_4.patch
```
Then I reset my changes to `mne-python`, `cd`ed to the `mne-qt-browser` dir, and checked that the `patch ...` command used here put my changes back where they belonged (and it did... after iterating on the command a bit!).

**Comment by drammock** [comment]
all green! 🎉

**Pull request merged**
