### PR TITLE
ENH: Epochs support

### PR DESCRIPTION
**Pull request by marsipu**
## Description
This is work in progress for epochs support.

- [x] adapt pyqtgraph-backend to IO for Epochs from mpl-backend
- [x] handle visualization
- [x] handle epochs-specific interaction (selecting bad epochs, etc.)
- [x] let pyqtgraph-backend pass `mne.viz.tests.test_epochs.py`

This PR depends on a [correspondent PR](https://github.com/mne-tools/mne-python/pull/10297) in mne-python.

<details>
<summary>Code I currently use for testing</summary>

```python
import mne
import os
import numpy as np

from mne.viz import use_browser_backend

# Load Raw
sample_data_folder = mne.datasets.sample.data_path()
raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                        'sample_audvis_raw.fif')
raw = mne.io.read_raw(raw_file)

# Load Events
events_path = os.path.join(sample_data_folder, 'MEG', 'sample',
                           'sample_audvis_raw-eve.fif')
events = mne.read_events(events_path)

# Add test-annotations
onsets = np.arange(2, 8, 2) + raw.first_time
durations = np.repeat(1, len(onsets))
descriptions = ['Test1', 'Test2', 'Test3']
for onset, duration, description in zip(onsets, durations, descriptions):
    raw.annotations.append(onset, duration, description)

epo = mne.Epochs(raw, events)

epoch_col1 = np.asarray(['b'] * len(epo.ch_names))
epoch_col1[::2] = 'r'
epoch_col2 = np.asarray(['r'] * len(epo.ch_names))
epoch_col2[::2] = 'b'
epoch_col3 = np.asarray(['g'] * len(epo.ch_names))
epoch_col3[::2] = 'b'
epoch_colors = np.asarray([['b'] * len(epo.ch_names) for _ in
                           range(len(epo.events))])
epoch_colors[::3] = epoch_col1
epoch_colors[1::3] = epoch_col2
epoch_colors[2::3] = epoch_col3
epoch_colors = epoch_colors.tolist()

with use_browser_backend('pyqtgraph'):
    epo.plot(block=True, n_epochs=10, events=events, epoch_colors=epoch_colors,
             precompute=False)
```
</details>

**REMINDER**: CI testing with the PR branch from mne-tools/mne-python#10297 has to be reverted before merging!

### CODE REVIEW

**Comment by marsipu** [comment]
Locally all tests are green now for me 😊 
The CIs are not green yet, because this PR is codependent with mne-tools/mne-python#10297.
@larsoner This one should probably be merged first, right?

**Comment by marsipu** [comment]
Everything seems to pass except `test_epochs.py::test_plot_epochs_ctf` for `macos`.

**Comment by marsipu** [comment]
The only issue remaining is #53.
I don't think I can find a solution for this until the release 1.0 of mne-python. It seems to be very tricky and I even don't know if it's a problem with `mne-qt-browser` or `PyQt5` with MacOS.
Do you think it would be bearable to set `use_opengl=True` by default for `epochs.plot()` or only for MacOS?

**Comment by marsipu** [comment]
@larsoner When you are fine I think we can merge this one

**Comment by marsipu** [comment]
The last CIs are bound to fail, because mne-tools/mne-python#10297 is not merged yet. But probably merging on mne-python's side first preferable

**Comment by larsoner** [comment]
I just merged, so maybe CIs just need to be restarted?

**Comment by marsipu** [comment]
maint/0.24 fails are expected, I will merge this one now

**Pull request merged**
