### PR TITLE
Fix x axis label text for Epochs (it used to say Time)

### PR DESCRIPTION
**Pull request by hoechenberger**
The text alignment is still wrong for me but at least the text itself is now correct for Epochs…

Screen Shot 2022-04-05 at 15 32 40

### CODE REVIEW

**Review by larsoner — APPROVED** [review]

**Comment by hoechenberger** [comment]
@larsoner I've changed it now such that the keyboard shortcut doesn't appear in the help either for Epochs
And when viewing raw data and toggling to "absolute" time, the x axis now has the label "Time of day"
WDYT?

**Comment by hoechenberger** [comment]
> "absolute time", or "datetime" (maybe too much jargon),

I fact, I'd love to display the time zone as well, and then I'd be happy with "Absolute time". But let's keep this for later, yes

**Comment by hoechenberger** [comment]
Good to go from my end

**Comment by larsoner** [comment]
Thanks @hoechenberger !

**Pull request merged**
