### PR TITLE
Update version to v0.3.2

### PR DESCRIPTION
**Pull request by marsipu**

### CODE REVIEW

**Comment by larsoner** [comment]
Feel free to auto-merge and continue with the release process @marsipu !

**Comment by marsipu** [comment]
@larsoner I support the stricter protection on `main`, but releasing takes now 2 PR. Is this intended?
Or is there a better way to do it than updating `_version.py` two times (`v0.4.dev0` -> `v.0.3.2` -> `v0.4.dev0`)?

**Comment by larsoner** [comment]
Feel free to remove the restriction about pushing directly to `main` if you sufficiently trust everyone with push access :)

Or do it temporarily for yourself around release time and then reenable it. But really I usually just make the PRs, if releases are infrequent it's not too bad

**Comment by marsipu** [comment]
I see, I trust you and `mne-qt-browser-admin` of course. I hope you trust me too :wink:

**Pull request merged**
